version: '2'
services:
  db:
    # Specify the database connection string in openKB config.json.
    # "database": {
    #     "type": "mongodb",
    #     "connection_string": "mongodb://openkb_user:openkb_pass@db-container:27017/openkb"
    # }
    image: mongo:4
    volumes:
      - ./volumes/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=openkb_user
      - MONGO_INITDB_ROOT_PASSWORD=openkb_pass

  app:
    image: toras9000/openkb
    build: ./build
    links:
      - db:db-container
    ports:
      - "8002:4444"
    volumes:
      - ./volumes/app/config:/openkb/config
